version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Build
          command: python3.7 -c "print('Built')"
workflows:
  version: 2
  run_tests:
    jobs:
      - build
